server:
   port: 8082
#主数据库
spring:
  application:
    name: springboot_test
  datasource:
      #springBoot2.0默认数据连接池是hikari
      druid:
        url: jdbc:mysql://localhost:3306/spring_boot_test1?characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        max-active: 100
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 1 FROM DUAL
        validation-query-timeout: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 100000
  jpa:
    show-sql: false
    #自动创建表结构，用于自动创建、更新、验证数据库表结构。
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  aop:
    auto: true
    proxy-target-class: false
  mail:
    host: smtp.qq.com
    username: 2550462328@qq.com
    password: vppfqakwjlkzeaie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #activemq配置
  activemq:
    broker-url: tcp://localhost:61616?jms.alwaysSyncSend=false&jms.useAsyncSend=true
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false
  #强制设置缓存类型
  cache:
    type: ehcache
  mvc:
    static-path-pattern: /**
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  #kafka配置
  kafka:
    # 指定kafka 代理地址，可以多个
    bootstrap-servers: 127.0.0.1:9999
    producer:
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 16384
      # 缓存容量
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # 指定默认消费者group id
      group-id: consumer-test
      auto-commit-interval: 100
      auto-offset-reset: earliest
      enable-auto-commit: false
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 指定listener 容器中的线程数，用于提高并发量
      concurrency: 3
  freemarker:
    cache: false
    template-loader-path: classpath:/static/ftl/
    suffix: .ftl
    enabled: true
    charset: UTF-8
    content-type: text/html
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

management:
  server:
    #actuator端口
    port: 9091
    servlet:
      context-path: /
  endpoints:
    web:
      #修改访问路径
      base-path: /actuator
      exposure:
        include: "*"
        #exclude: env,beans
      #开放所有页面节点  默认只开启了health、info两个节点
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: always
# #ldap配置
#  ldap:
#    urls:
#    base:
#    username:
#    password:

# #连接JNDI数据源
# jndi-name: java:jboss/datasources/customers

#配置springboot自带的Commons-logging
#logging:
#  #输出文件名
#  file:
#  #输出路径
#  path:
#  #日志级别
#  level: info

##次数据库
#spring.datasource.secondary:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/spring_boot_test2
#      username: root
#      password: root

#druid连接池 Mybatis连接
#spring:
#    datasource:
#        name: mysql_test
#        type: com.alibaba.druid.pool.DruidDataSource
#        #druid相关配置
#        druid:
#          #监控统计拦截的filters
#          filters: stat
#          driver-class-name: com.mysql.jdbc.Driver
#          #基本属性
#          url: jdbc:mysql://127.0.0.1:3306/spring_boot_test1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#          username: root
#          password: root
#          #配置初始化大小/最小/最大
#          initial-size: 1
#          min-idle: 1
#          max-active: 20
#          #获取连接等待超时时间
#          max-wait: 60000
#          #间隔多久进行一次检测，检测需要关闭的空闲连接
#          time-between-eviction-runs-millis: 60000
#          #一个连接在池中最小生存的时间
#          min-evictable-idle-time-millis: 300000
#          validation-query: SELECT 'x'
#          test-while-idle: true
#          test-on-borrow: false
#          test-on-return: false
#          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#          pool-prepared-statements: false
#          max-pool-prepared-statement-per-connection-size: 20
#    flyway初始化数据库地址
#    flyway:
#      locations: classpath:/db

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: cn.ictt.zhanghui.springboot_test.pojo

# pagehelper
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#    returnPageInfo: check

